### ISSUE TITLE
No icons for Play, Previous and Next

### ISSUE THREAD

**Issue by RagglenLove** [flathub/org.gmusicbrowser.gmusicbrowser#4]
![Screenshot_2021-11-06_09-21-05](https://user-images.githubusercontent.com/45503845/140593740-e4131414-e890-4a0b-882f-974df3b1bb01.png)

Downloaded from [Flathub](https://www.flathub.org/apps/details/org.gmusicbrowser.gmusicbrowser) and tested on both Xubuntu 20.04 LTS and Zorin OS 15.3 Lite.

As you can see in the screenshot, the icon for "Stop" is there, but the icons for "Play", "Previous" and "Next" are missing.

**Comment by BeatLink** [comment]
I have updated flatpak to point to the latest version, hopefully that should resolve the issue.

**Comment by RagglenLove** [comment]
I updated gmusicbrowser a couple of minutes ago, still the same issue.

**Comment by squentin** [comment]
Sorry, it's a known issue with the current version that I still haven't fixed, it affects icons that have a direction (left-to-right or right-to-left).
It doesn't affect themed icons (preferences->layouts->icon theme, currently requires a restart), so you can use that in the meantime.

**Comment by RagglenLove** [comment]
> Sorry, it's a known issue with the current version that I still haven't fixed, it affects icons that have a direction (left-to-right or right-to-left). It doesn't affect themed icons (preferences->layouts->icon theme, currently requires a restart), so you can use that in the meantime.

Thanks for the heads up and the help on getting the Play and other icons back.

**Comment by BeatLink** [comment]
Closing this issue
